apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mehrdadrad/frontend:latest
        imagePullPolicy: Always
        env:
        - name: MIDDLEWARE
          value: http://middleware.default.svc.cluster.local:8081/time
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: frontend
