apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-deployment
  labels:
    app: middleware
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: mehrdadrad/middleware:0.1
        env:
        - name: BACKEND
          value: http://backend.default.svc.cluster.local:8080/time
        ports:
        - containerPort: 8081		
---
apiVersion: v1
kind: Service
metadata:
  name: middleware
  labels:
    app: middleware
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: middleware
